spring.application.name=eventapp-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/eventapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=${APP_JWT_SECRET:THIS_IS_A_LOCAL_DEVELOPMENT_SECRET_KEY_FOR_EVENTAPP_123456789}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
app.jwt.refresh-expiration-ms=${APP_JWT_REFRESH_EXPIRATION_MS:604800000}

app.google.web-client-id=${GOOGLE_WEB_CLIENT_ID:830319667435-2d7s2ncq99ck0jvit6bqh5tk9dni24qi.apps.googleusercontent.com}
